name: Transpile/Build TypeScript

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./dev

    strategy:
      matrix:
        var:
          - input: game.ts
            output: ../JS/tsc/game.js

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install TypeScript
      run: npm install typescript

    - name: Transpile TypeScript
      run: npx tsc ${{ matrix.var.input }} --outFile ${{ matrix.var.output }}
        
