name: Transpile/Build TypeScript

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./dev

    strategy:
      matrix:
        var:
          - input: game.ts
            output: ../JS/tsc/game.js
          - input: infernum.ts
            output: ../JS/tsc/infernum.js

    steps:
    - uses: actions/checkout@v4
      with: 
        persist-credentials: false
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install TypeScript
      run: npm install typescript

    - name: Transpile TypeScript
      run: npx tsc ${{ matrix.var.input }} --outFile ${{ matrix.var.output }} --lib dom,es2024

    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git fetch
        git pull
        git add ${{ matrix.var.output }}
        git commit -m "${{ github.event.head_commit.message }}"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
